apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # Pods con label 'app: users'
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080 # Puerto que se expone
    targetPort: 8080 # Puerto que expone el contenedor
