apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template: 
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: toledo1082/kub-demo-auth:latest