# 1.1. Versión de este recurso que creamos
apiVersion: apps/v1
# 1.2. Indicamos que objeto queremos crar
kind: Deployment # Service, Job, etc.
# 1.3. Configuración de metadata del deployment (nombre, etc)
metadata:
  name: second-app-deployment
# 1.4. Especificación de información del Deployment (del object)
spec:
  # 1.5. Número de replicas de Pods en el Deployment
  replicas: 1
  # 1.13. Indicamos los selectores de Pods que controlará este Deployment
  selector:
    # 1.14. Indicamos que este deployment controlará todos los Pods que tengan los mismos labels que el Deployment (1.8)
    matchLabels:
      app: second-app
      tier: backend
  # 1.6. Indicamos el template que usarán los Pods (cambiamos a modificar objeto Pod), se crearn conforme se crea el Deployment
  template: 
    # kind: Pod # 1.6.1. Valor predefinido dentro de un kind:Deployment, no debe de ponerse
    # 1.7. Configuración de metadata del Pod (nombre, etc)
    metadata:
      # 1.8. Podemos colocar los label que queramos a los Pods.
      labels: 
        app: second-app
        tier: backend
    # 1.9. Especificación de información del Pod (del object)
    spec:
      # 1.10. Definimos la lista de contenedores dentro del Pod (puede ser más de uno pero normalmente 1 Pod por 1 contenedor)
      containers: 
        # 1.11. Nombre del contenedor
        - name: second-node
          # 1.12. Imagen que usa el contenedor second-node
          image: toledo1082/kub-action-01-starting-setup:3
        # Puede agregar más contenedores
        # - name: ...
        # - name: ...